### ISSUE TITLE
我也用的这个本本，想请教一下CLOVER换了你提供的这个之后，BIOS要改哪些？

### ISSUE THREAD

**Issue by 19317362** [MacsedProtoss/hackintosh#1]
我现在CLOVER引导安装以后，卡住了。还不会进入-v模式
可能和BIOS有关吧。请问一下BIOS怎怎么配置？
我的QQ:19317362
多谢!

网卡不换的话，有线网卡能驱动不能？

**Comment by MacsedProtoss** [comment]
BIOS 只要关闭Secure boot 即可，其他基本不用动
-v就是在clover界面 按空格 然后用下键移动到-v之后按回车选中，再esc 然后再回车即可
有线网卡已经驱动了

**Comment by MacsedProtoss** [comment]
对了 记得把无线网卡相关的驱动删掉，这是会卡住的原因之一

**Comment by MacsedProtoss** [comment]
seems the problem has been thesolved
