### ISSUE TITLE
我是295的声卡，但是一直没成功，用了你的这个也一样，要奔溃了...

### ISSUE THREAD

**Issue by NiceSmall** [MacsedProtoss/hackintosh#2]
求帮助。Q1024649179

**Comment by MacsedProtoss** [comment]
295有好多layout，可以换着看看

**Comment by NiceSmall** [comment]
我解决了 谢谢你的回复^ ^




| |
motou2017
|
|
邮箱：motou2017@163.com
|

Signature is customized by Netease Mail Master

在2019年03月19日 16:54，MacsedProtoss 写道：

295有好多layout，可以换着看看

**Comment by MacsedProtoss** [comment]
seems the issue has been solved
