### ISSUE TITLE
4k屏显示问题

### ISSUE THREAD

**Issue by wanggh1021** [MacsedProtoss/hackintosh#3]
我的是4K屏版本，CPU和你是同一版本，内存是单条16G
不知道你的屏幕在安装过程中是否下面有一条黑色的，无法显示的问题？
目前用的你的文件，但显卡一直无法驱动

**Comment by MacsedProtoss** [comment]
我没有这个显示问题
显卡不可以驱动的话，参考一下黑果小兵的教程改一下。通常不应该出现不可驱动的问题

**Comment by rote66** [comment]
问下楼主解决了吗，我这边也是4k版本，显卡无法驱动，改来改去不是常亮就是黑屏或者崩溃…:cry:

**Comment by wanggh1021** [comment]
> 问下楼主解决了吗，我这边也是4k版本，显卡无法驱动，改来改去不是常亮就是黑屏或者崩溃…😢

没有。。。太忙了，没时间折腾

**Comment by rote66** [comment]
@wanggh1021 整了几天解决了，调下framebuff就行，主要是被dvmt给绊住了:expressionless:

**Comment by wanggh1021** [comment]
> @wanggh1021 整了几天解决了，调下framebuff就行，主要是被dvmt给绊住了😑

牛掰~~  
下面是我秋秋，加个好友，向你学习学习
NDk2NTMzMzY=

**Comment by rote66** [comment]
> > @wanggh1021 整了几天解决了，调下framebuff就行，主要是被dvmt给绊住了😑
> 
> 牛掰~~
> 下面是我秋秋，加个好友，向你学习学习
> NDk2NTMzMzY=

害，我也就个小白，我的是15vg5的4k，efi已经传到我的库里了
